// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZAB7LBDOM6Sf96hTbKJEGEi65KBurbjI',
    appId: '1:264916224833:web:1ed224ec25f89ccb002fc0',
    messagingSenderId: '264916224833',
    projectId: 'healthform-4c43a',
    authDomain: 'healthform-4c43a.firebaseapp.com',
    storageBucket: 'healthform-4c43a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMihpsv6_WFAUs22r8LNq2OxELQhggPNY',
    appId: '1:264916224833:android:f4432eedc35126f7002fc0',
    messagingSenderId: '264916224833',
    projectId: 'healthform-4c43a',
    storageBucket: 'healthform-4c43a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyNf7f2PMXvJO1RMLQrD99-oN1FyFv5k',
    appId: '1:264916224833:ios:7f854f5ac3aeae9f002fc0',
    messagingSenderId: '264916224833',
    projectId: 'healthform-4c43a',
    storageBucket: 'healthform-4c43a.appspot.com',
    iosBundleId: 'com.example.healthForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyNf7f2PMXvJO1RMLQrD99-oN1FyFv5k',
    appId: '1:264916224833:ios:6d3d9a02b6aae16e002fc0',
    messagingSenderId: '264916224833',
    projectId: 'healthform-4c43a',
    storageBucket: 'healthform-4c43a.appspot.com',
    iosBundleId: 'com.example.healthForm.RunnerTests',
  );
}
